name: Publish on my server

on:  
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v1
      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0	
        with:
          playbook: ansible/deploy.yml
          directory: ./
          key: ${{ secrets.ansible_ssh_private_key }}
          inventory: ${{ secrets.ansible_inventory }}
