name: Publish on my server

on:  
  push:
    tags:
      - '*'

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@2.5.0
        with:
          playbook: ansible/deploy-playbook.yml
          directory: ./
          key: ${{ secrets.ansible_ssh_private_key }}
          inventory: ${{ secrets.ansible_inventory }}
