name: Publish on my server

on:  
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do some checking
        shell: bash
        run: |
          dir ./
          echo "the inventory ${{ secrets.ANSIBLE_INVENTORY }}"
      - name: Run ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0	
        with:
          playbook: ansible/deploy.yml
          directory: ./
          key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.ANSIBLE_INVENTORY }}
